### ISSUE TITLE
Improving documentation / README

### ISSUE THREAD

**Issue by dbrrt** [matthewmueller/next-cookies#10]
Is that project still maintained? If so it'd be great to improve the existing documentation.

**Comment by nfriedly** [comment]
It is being maintained, but not actively developed. 

There's not a whole lot to this project, and I don't anticipate adding much to it. 

However additional documentation is always welcome :)

**Comment by dbrrt** [comment]
I can provide some on documentation for this library if it can be at the end, easier to integrate in nextjs framework.

**Comment by skdigital** [comment]
Anyone looking to update the docs? No offense and all but they are absolutely spartan. I would find it easier navigating a Chinese community shopping center than actually getting this cookie to work in my super simple next project. These docs hardly beginner friendly, I would put in a PR to change things up but I am a noob lol.
