### ISSUE TITLE
How to Write, Delete

### ISSUE THREAD

**Issue by mehrdad-shokri** [matthewmueller/next-cookies#17]
The README provides an example for reading. ``const { token } = cookies(ctx)``
how to write or delete a cookie?

**Comment by coder054** [comment]
write: document.cookie = "token=whatever"

**Comment by mehrdad-shokri** [comment]
Will this not remove other present cookies?

**Comment by nfriedly** [comment]
Nope, cookies are wierd. Setting `document.cookie` will either add a new cookie or else overwrite an existing one if it has the same name (and path and domain...)

You probably want to set `path=/` and `domain=.your domain.com` to avoid having duplicates. And possibly the expiration date to make it last longer.

To delete a cookie, do the same thing but set the expiration date in the past.

**Comment by mehrdad-shokri** [comment]
@nfriedly yeah, I ended up using ``js-cooki`` along side this project. Thank you
