### ISSUE TITLE
problem when get cookie has special character

### ISSUE THREAD

**Issue by drcuong** [matthewmueller/next-cookies#20]
import cookie from 'js-cookie';
import nextCookie from 'next-cookies'        

cookie.set('access_token', 'SEnxqTgooNWEFfQ9gUipwdhUrZm1VejMLDQ==');
        const {access_token} = nextCookie(this);
        console.log('test ' + access_token); // show SEnxqTgooNWEFfQ9gUipwdhUrZm1VejMLDQ
        console.log('test 2' + cookie.get('access_token')); //show  SEnxqTgooNWEFfQ9gUipwdhUrZm1VejMLDQ==

nextCookie can not get special character '==' at the end of string

**Comment by nfriedly** [comment]
It looks like this is a big in the underlying component-cookie library:

https://github.com/component/cookie/blob/08d42f4ae257a6d09f965f6e9c6c8be9fb4b4c71/index.js#L103-L104

It removes all `=` with the `.split()` when it only wants the first one. I'll send them a PR.

**Comment by nfriedly** [comment]
This should be fixed in v2.0.0, just now published to npm. (I switched to a different underlying library, hence the semver-major bump.)

Can you test and confirm?

**Comment by himadrinath** [comment]
@nfriedly how to extract token with character "."
like this one "msal.idtoken"
