### ISSUE TITLE
The old browser will fail due to the use of "let".

### ISSUE THREAD

**Issue by bkm412** [matthewmueller/next-cookies#25]
https://github.com/matthewmueller/next-cookies/blob/b2c0d5e7e316054dc39df07538a75c8fa82762ea/index.js#L1

I run a service that supports the version 4.x "Android." Because "node_modules" is ignored in babel option, an error occurs because the old browser does not understand 'let'.
This forced me to use another alternative library. Do you happen to have any plans to change?

**Comment by nfriedly** [comment]
Op, sorry about that. It's fixed now, and I changed the ESLint config to only alow ES5 in library code going forwards. Fix should be released to npm as v2.0.3 once the CI loop finishes.
