### ISSUE TITLE
JSON encoded values are automatically parsed?

### ISSUE THREAD

**Issue by cullylarson** [matthewmueller/next-cookies#26]
I have a cookie whose value is a JSON encoded string. When I retrieve the cookie using `next-cookies`, I get an object instead of a string. I wouldn't expect the JSON string to be parsed automatically, and it doesn't seem to be documented.

Cookies header is set to: `blah=%7B%22foo%22%3A%22asdf%22%7D`

Expected `nextCookie` to return:

```
{
  blah: '{"foo":"asdf"}'
}
```

Instead got:

```
{
  blah: {
    foo: "asdf"
  }
}
```

**Comment by nfriedly** [comment]
Hi, sorry for the confusion and the delay. This behavior can be disabled by passing an options object like so:

```js
const allCookies = cookies(ctx, {doNotParse: true});
```

I'll update the readme to document this.
