### ISSUE TITLE
About getInitialProps in ReadMe

### ISSUE THREAD

**Issue by tomsoderlund** [matthewmueller/next-cookies#31]
I think ReadMe should say `static async getInitialProps({ ctx })`, not `static async getInitialProps(ctx)`

**Comment by nfriedly** [comment]
I don't think so (?) The test app works without any destructuring:

https://github.com/matthewmueller/next-cookies/blob/777b5cc9be15c935914fcfc6ed3234858afe23b9/tests/test-app/pages/cookies.js#L16-L18

`ctx` is the name of the top-level object, not one of the keys, and next-cookies expects the top-level object.

I suppose if you wanted to destructure it, you could do something like this:

```js
// ...
static async getInitialProps({ req }) => {
  let cookies = cookies({ req });
  // do stuff with cookies...
}
// ...
```

But that's just the same result with a bit of extra work.

**Comment by tomsoderlund** [comment]
@nfriedly Hmm weird, because the top level context prop contains children `{ ctx, req }` etc, and for me `cookies(ctx)` works but `cookies(topLevelContext)` does not.

**Comment by tomsoderlund** [comment]
Maybe Next.js version issue? I'm using 9.3.3.

**Comment by nfriedly** [comment]
That is odd. The current docs say that it is a top-level object, but if it's working the other way for you, then I'm not sure what's going on.

https://nextjs.org/docs/api-reference/data-fetching/getInitialProps
