### ISSUE TITLE
Add deprecation notice due to Next.js 10.0.4 having cookies in `getServerSideProps`?

### ISSUE THREAD

**Issue by karlhorky** [matthewmueller/next-cookies#38]
Hi there, thanks for this package! I've been happily using it and also teaching with it in the @upleveled bootcamp.

It seems like `next@10.0.4` has support for `req.cookies` without any library: https://github.com/vercel/next.js/pull/19724

Would you consider deprecating this library and referencing the changes in the new version?

**Comment by shunkakinoki** [comment]
This seems like a good idea!

**Comment by nfriedly** [comment]
Hey, sorry this slipped through the cracks.

From a quick glance, it appears that next.js only provides the cookies during server-side-rendering, whereas this plugin provides them in both client and server code.  So, unless I missed something, I don't think it makes sense to deprecate this module just yet.

**Comment by karlhorky** [comment]
Oh, how would it be used for getting cookies in client-side rendering?

**Comment by nfriedly** [comment]
```js
const allCookies = cookies(ctx);
```

It's the exact same API for client and server, that's kind of the point of this library.

**Comment by karlhorky** [comment]
I meant to ask about a use case for this... so, where and why would this code be used on the client?

**Comment by karlhorky** [comment]
Or are you talking about the older `getInitialProps`, which is recommended to avoid in the docs?

**Comment by nfriedly** [comment]
You should really take a look at the readme, I think it would clarify things for you.

> The ctx object is passed to your getInitialProps function by next.js.

This lib doesn't really make sense with `getServerSideProps` because it's for using the same code on client and server, whereas `getServerSideProps` is server side only.

Sometimes you just want to read the cookie value and render the page without caring about if it's on the client or on the server. That's when this library is useful.

**Comment by karlhorky** [comment]
I did look at the readme, it seems to do with the older `getInitialProps`.

What this issue is about is the currently recommended style of Next.js - `getServerSideProps` and `getStaticProps`.

It doesn't seem that this library adds anything there.

Now that `context` includes `cookies` in the `req` object, anywhere you have a `ctx`, you'll already have the cookies.

So I don't see what your point is here.

**Comment by nfriedly** [comment]
I feel like we're going in circles here. Let's just say that this library isn't a good fit for your needs and leave it at that.

**Comment by karlhorky** [comment]
Yeah, I was just asking for a demo of how client-side context would make sense with the recommended `getServerSideProps` and `getStaticProps`.

But no worries, if this library is intended for the older `getInitialProps`, that's fine too!

My main point is that this could be pointed out in the readme, so that users are directed towards recommended paths, instead of sticking with older APIs (which could eventually be deprecated) :)

But seems like I can't convince the maintainers here, so all good.
